/* Main.c file generated by New Project wizard
 *
 * Created:   Tue Nov 19 2024
 * Processor: LPC1114FBD48/301
 * Compiler:  GCC for ARM
 */

/*

 Name: Nizar Bassam Lubbad

 ID: 120180187

*/

#define GPIO0DIR (*((volatile unsigned long *)0x50008000))
#define GPIO0DATA (*((volatile unsigned long *)0x50003FFC))

// #include <LPC11xx.h>

int main(void)
{

    GPIO0DIR |= 0b0100;
    GPIO0DATA = 0b0000;
    // Write your code here
    while (1)
    {
        if (GPIO0DATA & 0b10)
        {
            GPIO0DATA = 0b100;
        }
        else if (GPIO0DATA & 0b1000)
        {
            GPIO0DATA = 0b000;
        }
    }

    return 0;
}
